version: '3'

services:
  redis:
    image: "redis:alpine"
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: metabolic
    volumes:
      - .:/metabolic
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery:
    build: .
    command: celery -A rivm2016 worker -l info
    volumes:
      - .:/metabolic
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A rivm2016 beat -l info
    volumes:
      - .:/metabolic
    depends_on:
      - redis
